version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            export CI_BRANCH=$CIRCLE_BRANCH
            export PACKAGECLOUD_REPOSITORY=dokku/dokku
            make version
      - run: make ci-report
      - run: make build-docker-image
      - run:
          command: |
            make build-in-docker
            [[ -d build ]] && sudo chown -R circleci:circleci build
      - run: make validate-in-docker
      - store_artifacts:
          path: build
          destination: build
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release-in-docker release-packagecloud-in-docker
            fi
